<?php
	/* Fichier de traduction de l'admin */ 

	
	function _tr($t) { 
	$tr_ = array(
		'Online' => 'En ligne',
	'Hello'	=> 'Bonjour',
	'Logout' => 'Se déconnecter',
	'Click in the left menu to start.' => 'Cliquez dans le menu pour commencer.',
	'Save'	=> 'Sauver',
'Profil Saved'	=> 'Profil sauvé',
'delete'	=> 'Effacer',
'Slug name'	=> 'Nom simplifié',
'Name'	=> 'Nom',
'New template' =>'Créer un template',

'Description'	=> '',
'Dashboard'	=> '',
'New post'	=> 'Nouveau Billet',
'All posts'	=> 'Tous les billets',
'Categories'	=> 'Catégories',
'New product'	=> 'Nouveau produit',
'All products'	=> 'Tous les produits',
'Topics'	=> 'Sujets',
'STUDIO'	=> '',
'New project'	=> 'Nouveau projet',
'All projects'	=> 'Tous les projets',
'Groups'	=> 'Groupes',
'PAGES'	=> '',
'New page'	=> 'Nouvelle page',
'All pages'	=> 'Les pages',
'Templates'	=> '',
'EDITION'	=> 'EDITION',
'Editor'	=> 'Editeur',
'ADMINISTRATION'	=> 'ADMINISTRATION',
'Users'	=> 'Utilisateurs',
'Translate'	=> 'Traductions',
'You have received a new message from your website contact form'	=> 'Vous avez reçu un nouveau message depuis votre formulaire de contact.',
'Sunday'	=> 'Dimanche',
'Monday'	=> 'Lundi',
'Tuesday'	=> 'Mardi',
'Wednesday'	=> 'Mercredi',
'Thursday'	=> 'Jeudi',
'Friday'	=> 'Vendredi',
'Saturday'	=> 'Samedi',
'January'	=> 'Janvier',
'February'	=> 'Février',
'March'	=> 'Mars',
'April'	=> 'Avril',
'May'	=> 'Mai',
'June'	=> 'Juin',
'July'	=> 'Juillet',
'August'	=> 'Août',
'September'	=> 'Septembre',
'October'	=> 'Octobre',
'November'	=> 'Novembre',
'December'	=> 'Décembre',
'Wrong format'	=> 'Mauvais format',
'Image too Big'	=> 'Image trop lourde',
'Bad picture'	=> 'Mauvais format d\'image',
'already exists'	=> 'Existe déjà',
'Add Picture'	=> 'Ajouter',
'Uploading'	=> 'Téléchargement',
'Add a new post'	=> 'Nouveau billet',
'Edition'	=> '',
'Posts'	=> 'Billets',
'Posts list'	=> 'Liste de billets',
'Date'	=> '',
'Post'	=> 'Article',
'visible'	=> '',
'showcase'	=> '',
'closed'	=> 'fermé',
'Add a new product'	=> 'Nouveau produit',
'Product'	=> 'Produits',
'products list'	=> 'Liste de produits',
'All Messages'	=> 'Tous les messages',
'Admin'	=> 'Admin',
'Contact'	=> 'Contact',
'Edit a page'	=> 'Editer une page',
'Newsletter'	=> 'Newsletter',
'Créer un template'	=> '',
'All E-mails'	=> '',
'Mailing list'	=> '',
'Add a new page'	=> 'Nouvelle page',
'page'	=> '',
'Pages list'	=> 'Liste de pages',
'Pages'	=> 'Pages',
'Plugins'	=> '',
'Add a new item'	=> 'Nouvel élément',
'Items'	=> 'Eléments',
'Add a new project'	=> 'Nouveau projet',
'projects list'	=> 'Liste des projets',
'Texts'	=> 'Textes',
'Add Member'	=> 'Ajouter un membre',
'Show password'	=> '',
'Add'	=> '',
'Modify Member'	=> '',
'Click here if you are sure you want to delete'	=> '',
'Change password'	=> 'Affichez le mot de passe',
'E-mail'	=> '',
'Password'	=> 'Mot de passe',
'Retype password'	=> 'Retaper le mot de passe',
'Edit'	=> 'Modifier',
'New user'	=> 'Nouvel utilisateur',
'Users list'	=> '',
'User'	=> '',
'Status'	=> 'Statut',
'Editeur'	=> '',
'Profil'	=> '',
'Pass'	=> '',
'Delete'	=> 'Effacer',
'Sent'	=> 'Envoyé',
'Add' => 'Ajouter'

	);
	if(!empty($tr_[$t])) return $tr_[$t]; else return $t;
	}

	function _t($t) {
		echo _tr($t);
		
	}	
	?>
